### PR TITLE
Fix #71 - Swallow existent file crash if symlink

### LINKED ISSUE #71: [Regression] Crash when apply backup on certain devices
## Preconditions
- Firefox Profile Manager is installed.
- Firefox is installed. 

## Steps to reproduce
1. Open FPM and create a new backup.
2. Go to Firefox and change the settings -> close the browser.
3. Go to FPM and swipe from left to right for the backup added at step 1.
4. Tap on "Apply". 

### Expected behavior
The backup is applied. 

### Actual behavior
The FPM crashes. 

Logcat1:
2020-01-27 11:01:50.699 24286-24286/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fpm, PID: 24286
    java.io.FileNotFoundException: /data/user/0/org.mozilla.firefox/lib/libplugin-container.so (Permission denied)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
        at org.mozilla.fpm.utils.ZipUtils.extract(ZipUtils.java:92)
        at org.mozilla.fpm.data.BackupRepositoryImpl.deploy(BackupRepositoryImpl.kt:124)
        at org.mozilla.fpm.presentation.mvp.MainPresenter$applyBackup$1$1.invokeSuspend(MainPresenter.kt:45)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

Logcat2:
[BetaCrashApply.txt](https://github.com/mozilla-mobile/fennec-profile-manager/files/4116273/BetaCrashApply.txt)

### Note
On devices with android >5, the backup is duplicated with "-temp" extension added to the name.

### Device information
* Android device: Huawei Honor 8 (Android 7.0), Sony Xperia Z5 Premium (Android 7.1.1), Nokia 6 (Android 7.1.1), Motorola Moto G6 (Android 8).
* Build Firefox Profile Manager v1.0 for Fennec Release, Beta and Nightly.

### PR DESCRIPTION
**Pull request by Mugurell**
On some devices the data/data/app_package/lib directory is just a symlink while
on other devices that directory contains the actual extracted libs.
The actual files can be overwritten by us.
The symlinked files (and directory) is only readable by us and so when trying
to create a new FileOutputStream for such a file we would get a
FileNotFoundException.
To avoid crashing in such scenarios we'll swallow the exception if and only if
we can confidently know the file exists, just we don't have write access to it.

### CODE REVIEW

File: app/src/main/java/org/mozilla/fpm/utils/ZipUtils.java [hunk 1]
```diff
@@ -89,17 +89,26 @@ public void extract(String zipFile, String destinationDir) throws IOException {
...
+                    // Do a speculative check that the file that caused the exception is one such symlinked file.
+                    if (destFile.exists() && destFile.length() > 0 && !destFile.canWrite()) {
+                        Log.w(LOGTAG, "Could not write " + destFile.getName() + ". Ignoring.");
+                    } else {
+                        throw e;
+                    }
                 }
-                dest.flush();
-                dest.close();
-                is.close();
```
Comment (andlzr) [inline app/src/main/java/org/mozilla/fpm/utils/ZipUtils.java:102]: Forgot to close input stream.
